---
title: "Lab Name"
author: "Author Name"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(alarmdata)
library(redist)
library(dplyr)
library(ggplot2)
library(ggredist)
library(ggplot2)
library(patchwork) # for plotting
MO <- alarm_50state_map('MO')
MO <- map_MO |>
    mutate(vote_tot = nrv + ndv)
```

### Exercise 1

http://127.0.0.1:16989/library/redist/doc/redist.html  n         

```{r code-chunk-label}
MO <- MO |>
    group_by(county) |>
    summarise(
        # population
        pop        = sum(pop),
        pop_hisp   = sum(pop_hisp),
        pop_white  = sum(pop_white),
        pop_black  = sum(pop_black),
        pop_aian   = sum(pop_aian),
        pop_asian  = sum(pop_asian),
        pop_other  = sum(pop_other),
        # voting age population
        vap        = sum(vap),
        vap_hisp   = sum(vap_hisp),
        vap_white  = sum(vap_white),
        vap_black  = sum(vap_black),
        # elections
        pre_16_rep_tru = sum(pre_16_rep_tru),
        pre_16_dem_cli = sum(pre_16_dem_cli),
        uss_18_rep_haw = sum(uss_18_rep_haw),
        uss_18_dem_mcc = sum(uss_18_dem_mcc),
        pre_20_rep_tru = sum(pre_20_rep_tru),
        pre_20_dem_bid = sum(pre_20_dem_bid),
        ndv        = sum(ndv),
        nrv        = sum(nrv),
        vote_tot   = sum(vote_tot),
        area_land  = sum(area_land),
        cd_2020    = mean(cd_2020),
        # dissolve precinct geometries into county shapes
        geometry   = st_union(geometry),
        .groups = "drop"
    )

map_MO = redist_map(MO, existing_plan=cd_2020, pop_tol=0.01, total_pop = pop, adj = MO$adj)
plot(map_MO, adj=TRUE) + plot(map_MO)
```

### Exercise 2
```{r}
areas = as.numeric(units::set_units(sf::st_area(map_MO$geometry), mi^2))
plot(map_MO, fill = pop / areas) + 
    scale_fill_viridis_c(
    name   = "Population density (people / sq. mi)",
    trans  = "sqrt",
    labels = scales::comma,
    breaks = c(0, 200, 1200, 3000, 5000),
    limits = c(0, 5000)          
)
.
max(map_MO$pop / areas)
```

...
```{r}
plot(iowa_map, fill = dem_08 / tot_08) +
    scale_fill_gradient2(name="Pct. Democratic '08",  midpoint=0.5)


plot(iowa_map, fill = wvap / vap, by_distr = TRUE)

redist.plot.plans(iowa_plans, draws=1:6, shp=iowa_map)

```

