---
title: "new_NY"
output: html_document
---

```{r}
library(alarmdata)
library(redist)
library(dplyr)
library(ggplot2)
library(ggredist)
library(ggplot2)
library(sf)
library(patchwork) # for plotting...
map_NY <- alarm_50state_map('NY')
map_NY <- map_NY |>
    mutate(vote_tot = nrv + ndv) |>
    mutate(dem_perc = ndv / vote_tot)
```



```{r}
southern_ny_counties <- c("New York County", "Kings County", "Queens County", "Bronx County", "Richmond County", "Nassau County")
```

```{r}
plot(map_NY, adj = TRUE) + plot(map_NY)
```


```{r}
areas = as.numeric(units::set_units(sf::st_area(map_NY$geometry), mi^2))
plot(map_NY, fill = pop / areas) + 
    scale_fill_viridis_c(
    name   = "Population density (people / sq. mi)",
    trans  = "sqrt",
    labels = scales::comma,
    breaks = c(0, 20000, 70000, 200000),
    limits = c(0, 200000)
)

```


```{r}
my_cutpoints <- c(0,.35,.45,.49999,.5,.50001,.55,.65,1.00)
my_labels <- c("R+15 or more", "R+5 to R+15", "R+1 to R+5", "R+0 to R+1", 
               "D+0 to D+1", "D+1 to D+5", "D+5 to D+15", "D+15 or more")
my_colors <- c("#b2182b","#d6604d","#f4a582","#fddbc7",
                  "#d1e5f0","#92c5de","#4393c3","#174778")

map_NY <- map_NY |>
  mutate(margin = cut(dem_perc, breaks = my_cutpoints, labels = my_labels))

nyWaterBlocks <- NULL
for (i in seq_len(nrow(map_NY))) {
  if (map_NY$pop[i] <= 0) {
    nyWaterBlocks <- rbind(nyWaterBlocks, map_NY[i,])
  }
}

 ggplot(map_NY) +
  geom_sf(aes(fill = margin), color = alpha("black", 0.1), linewidth = 0.01) +
  scale_fill_manual("", values = my_colors) +
  geom_sf(
    data = nyWaterBlocks,
    fill = "#EBEBEB",
    color = NA)


```

```{r}

my_cutpoints <- c(0,.35,.45,.49999,.5,.50001,.55,.65,1.00)
my_labels <- c("R+15 or more", "R+5 to R+15", "R+1 to R+5", "R+0 to R+1", 
               "D+0 to D+1", "D+1 to D+5", "D+5 to D+15", "D+15 or more")
my_colors <- c("#b2182b","#d6604d","#f4a582","#fddbc7",
               "#d1e5f0","#92c5de","#4393c3","#2166ac")

map_NY_south <- map_NY |>
  filter(county %in% southern_ny_counties)

nyWaterBlocks <- NULL
for (i in seq_len(nrow(map_NY))) {
  if (map_NY$pop[i] <= 0) {
    nyWaterBlocks <- rbind(nyWaterBlocks, map_NY[i,])
  }
}
nyWaterBlocks <- map_NY_south |> filter(pop <= 0)

 ggplot(map_NY_south) +
  geom_sf(aes(fill = margin), color = alpha("black", 0.1), linewidth = 0.01) +
  scale_fill_manual("", values = my_colors) +
  geom_sf(
    data = nyWaterBlocks,
    fill = "#EBEBEB",
    color = NA)
```

```{r}



#broken??

my_cutpoints <- c(0,.35,.45,.49999,.5,.50001,.55,.65,1.00)
my_labels <- c("R+15 or more", "R+5 to R+15", "R+1 to R+5", "R+0 to R+1", 
               "D+0 to D+1", "D+1 to D+5", "D+5 to D+15", "D+15 or more")
my_colors <- c("#b2182b","#d6604d","#f4a582","#fddbc7",
               "#d1e5f0","#92c5de","#4393c3","#2166ac")
map_NY <- map_NY |>
  mutate(margin = cut(dem_perc, breaks = my_cutpoints, labels = my_labels))

nyWaterBlocks <- NULL
for (i in seq_len(nrow(map_NY))) {
  if (map_NY$pop[i] <= 0) {
    nyWaterBlocks <- rbind(nyWaterBlocks, map_NY[i,])
  }
}
nyWaterBlocks <- map_NY_south |> filter(pop <= 0)


 ggplot(map_NY_south) +
  geom_sf(aes(fill = ), color = alpha("black", 0.1), linewidth = 0.01) +
  scale_fill_manual("", values = my_colors) +
  geom_sf(
    data = nyWaterBlocks,
    fill = "#EBEBEB",
    color = NA)
```



```{r}
southern_ny_counties <- c("New York County", "Kings County", "Queens County", "Bronx County", "Richmond County", "Nassau County")

map_NY <- map_NY |>
  filter(pop > 0) |>
  mutate(
    minority_pop = pop_hisp + pop_black + pop_aian + pop_asian + pop_nhpi + pop_other + pop_two,
    minority_perc = ifelse(pop > 0, minority_pop / pop, NA))

map_NY_south <- map_NY |>
  filter(county %in% southern_ny_counties)

ggplot(map_NY_south) +
  geom_sf(aes(fill = minority_perc), color = alpha("black", 0.1), linewidth = 0.01) +
scale_fill_gradient("Minority %", 
                    low = "blue", high = "yellow",
                    labels = scales::percent,
                    na.value = "#EBEBEB")
  theme_void()
```



