# --BlockManager Utility--
# Author: Fletcher Green

#---------------------------------------------------------------------------------
# Section: Initialization
#---------------------------------------------------------------------------------

library(alarmdata)
library(tidyverse)
library(sf)
sf_use_s2(FALSE)

#---------------------------------------------------------------------------------
# Section: BlockManager Environment Creation
#---------------------------------------------------------------------------------

BlockManager <- local({
  
  retVal <- new.env()

  # --GetBlocks Function--
  # Description: Gets a states precinct blocks from the alarmdata package and removes
  #              unnecessary columns.
  # inName: Two leter abreviation of the desired state.
  # Return: Sf object containing geometry and GEOID columns.
  retVal$GetBlocks <- function(inName) {
    
    # Get sf object from alarmdata.
    newBlocks <- alarm_50state_map(inName)
    
    # Strip unnecessary info.
    newBlocks <- st_sf(
      GEOID = newBlocks$GEOID,
      geometry = st_geometry(newBlocks),
      crs = st_crs(newBlocks)
    )
    
    return(newBlocks)
  }
  
  # --JoinByGeoid Function--
  # Description: Joins block level data to block geometry.
  # Format Expected: inSf generated by GetBlocks member function. inData must have
  #                  a corresponding GEOID column.
  # inSf: The input sf object containing block level geometry.
  # inData: The input data to join by GEOID column.
  # Return: Sf object containing geometry, GEOID, and joined to desired data.
  retVal$JoinByGeoid <- function(inSf, inData) {
    inSf <- left_join(inSf, inData, by = "GEOID")
    return(inSf)
  }
  
  # --ConsolodateDistricts Function--
  # Description: Spatially joins block level data to desired district geometry.
  # Format Expected: blockSf contains only numeric data columns.
  # districtSf: Sf object containing district geometry to join to.
  # blockSf: Sf object containing block geometry to consolidate into districts.
  # Return: Sf object contining district geometry with consolodated block level data.
  retVal$ConsolodateDistricts <- function(districtSf, blockSf) {
    
    # Translate CRS and make blocks into centroids.
    districtSf <- st_make_valid(districtSf)
    centrailizedBlocks <- st_make_valid(blockSf)
    centrailizedBlocks <- st_transform(centrailizedBlocks, st_crs(districtSf))
    centrailizedBlocks <- st_point_on_surface(centrailizedBlocks)
    
    # Perform spatial join.
    districtSf <- st_join(
      districtSf,
      centrailizedBlocks,
      join = st_intersects
    )
    
    # Add up numeric data in columns.
    districtSf <- districtSf |>
      group_by(DISTRICT) |>
      summarize(across(where(is.numeric), sum, na.rm = TRUE))
    
    return(districtSf)
  }
  
  retVal
})